python:
  - "2.7"
sudo: required
dist: trusty
addons:
  apt:
    packages:
    - python-yaml
    - cmake
    - bison
    - flex
    - git
    - autoconf
    - automake
    - libtool
    - antlr
    - wget
    - fakeroot
install:
  - sudo update-ca-certificates -f
  - wget -q "http://dl.google.com/android/repository/android-ndk-r11c-linux-x86_64.zip" -O /tmp/ndk.zip
  - ( cd $HOME; unzip -q /tmp/ndk.zip; mv android-ndk-* .ndk )
before_script:
  - echo -e 'G_MAINTAINER="travis"\nG_NDKPATH="$HOME/.ndk"' > config.sh
  - export PYTHONPATH="/usr/lib/python2.7/dist-packages"
script:
  - ./botbrew toolchain
  - ./botbrew makefile > Makefile
  - make -s -k package-all
after_failure:
  - cat log/dcron
